import * as cheerio from 'cheerio';
import { createLogger } from '../utils/logger.js';

/**
 * Compliant HTTP + Cheerio scraper (docs/07). This is the real-source capability:
 * honest User-Agent, robots.txt honored, ≥1 req/2s rate limiting, facts-only extraction.
 * Selectors are per-source; wire a concrete source's selectors and enrich via the pipeline.
 * For JS-rendered sources, swap fetchHtml() for a Playwright page fetch.
 */
const logger = createLogger('scraper');
const USER_AGENT = 'TechFirmsBot/0.1 (+https://techfirms.com/bot)';

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

export async function fetchHtml(url: string, timeoutMs = 15000): Promise<string | null> {
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), timeoutMs);
  try {
    const res = await fetch(url, {
      signal: ctrl.signal,
      headers: { 'user-agent': USER_AGENT, accept: 'text/html,application/xhtml+xml' },
    });
    if (!res.ok) {
      logger.warn({ url, status: res.status }, 'non-200; treating as no data');
      return null;
    }
    return await res.text();
  } catch (err) {
    logger.warn({ url, err }, 'fetch failed');
    return null;
  } finally {
    clearTimeout(t);
  }
}

/** Minimal robots.txt check: honor a Disallow that matches the path prefix. Treat a challenge/no-file as allow. */
export async function robotsAllows(baseUrl: string, path: string): Promise<boolean> {
  const html = await fetchHtml(new URL('/robots.txt', baseUrl).toString(), 8000);
  if (!html) return true;
  const disallows = html
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => /^disallow:/i.test(l))
    .map((l) => l.split(':')[1]?.trim())
    .filter(Boolean) as string[];
  return !disallows.some((d) => d !== '' && path.startsWith(d));
}

export interface ScrapedCard { sourceId: string; url: string; name: string; website?: string; location?: string }
export interface ListingSelectors { card: string; name: string; website?: string; location?: string; profileHref?: string }

/**
 * Scrape one listing page into partial company cards. Rate-limited; robots-aware.
 * The returned cards are FACTS only — descriptions are regenerated by the pipeline (never copied).
 */
export async function scrapeListing(opts: {
  baseUrl: string;
  listPath: string;
  selectors: ListingSelectors;
  crawlDelayMs?: number;
}): Promise<ScrapedCard[]> {
  const { baseUrl, listPath, selectors } = opts;
  const crawlDelayMs = Math.max(opts.crawlDelayMs ?? 2000, 2000); // ≥1 req/2s

  if (!(await robotsAllows(baseUrl, listPath))) {
    logger.info({ baseUrl, listPath }, 'robots.txt disallows — skipping');
    return [];
  }
  await sleep(crawlDelayMs);

  const html = await fetchHtml(new URL(listPath, baseUrl).toString());
  if (!html) return [];

  const $ = cheerio.load(html);
  const cards: ScrapedCard[] = [];
  $(selectors.card).each((i, el) => {
    const $el = $(el);
    const name = $el.find(selectors.name).first().text().replace(/\s+/g, ' ').trim();
    if (!name) return;
    const href = selectors.profileHref ? $el.find(selectors.profileHref).first().attr('href') ?? '' : '';
    cards.push({
      sourceId: href || `${listPath}#${i}`,
      url: href ? new URL(href, baseUrl).toString() : new URL(listPath, baseUrl).toString(),
      name,
      website: selectors.website ? $el.find(selectors.website).first().attr('href') ?? undefined : undefined,
      location: selectors.location ? $el.find(selectors.location).first().text().trim() || undefined : undefined,
    });
  });
  logger.info({ listPath, found: cards.length }, 'scraped listing page');
  return cards;
}
