import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "How the Company Intelligence Score works",
  description: "TechFirms' Company Intelligence Score (CIS) is a transparent, deterministic composite of customer reviews (40%), employee sentiment (25%), trust signals (20%), and market activity (15%). Rankings are never for sale.",
};

const WEIGHTS = [
  { label: "Customer reviews", pct: 40, desc: "Verified client ratings across quality, schedule, cost, and willingness-to-refer, with Bayesian shrinkage for low counts and 12-month recency decay." },
  { label: "Employee sentiment", pct: 25, desc: "Aggregated workplace ratings (culture, compensation, work–life balance, leadership, % recommend). Aggregates only — we link out to the source." },
  { label: "Trust signals", pct: 20, desc: "Domain age, valid SSL, GitHub org activity, certifications, and funding raised." },
  { label: "Market activity", pct: 15, desc: "Review velocity and breadth as a proxy for market presence." },
];

export default function MethodologyPage() {
  return (
    <main className="mx-auto w-full max-w-3xl flex-1 px-6 py-12">
      <h1 className="text-3xl font-bold tracking-tight">How the Company Intelligence Score works</h1>
      <p className="mt-4 rounded-lg border border-border bg-muted/40 p-4 leading-relaxed">
        The Company Intelligence Score (CIS) is a transparent, 0–100 composite that ranks technology companies. It is computed <strong>deterministically</strong> from four weighted signals; the accompanying summary is AI-narrated but the number itself is never generated by an LLM. <strong>Rankings are never for sale</strong> — sponsorship never influences the CIS.
      </p>

      <h2 className="mt-10 text-xl font-semibold">The four signals</h2>
      <div className="mt-4 space-y-3">
        {WEIGHTS.map((w) => (
          <div key={w.label} className="rounded-lg border border-border bg-card p-4">
            <div className="flex items-center justify-between">
              <span className="font-medium">{w.label}</span>
              <span className="tabular font-semibold text-primary">{w.pct}%</span>
            </div>
            <div className="mt-2 h-1.5 rounded-full bg-muted"><div className="h-full rounded-full bg-brand-500" style={{ width: `${w.pct}%` }} /></div>
            <p className="mt-2 text-sm text-muted-foreground">{w.desc}</p>
          </div>
        ))}
      </div>

      <h2 className="mt-10 text-xl font-semibold">Leaderboards & quadrants</h2>
      <p className="mt-3 text-muted-foreground">
        Companies are ranked within <strong>country × service</strong> cohorts using a median split, and placed into four quadrants by Market Presence (x) and Client Satisfaction (y): <strong>Leaders</strong>, <strong>Challengers</strong>, <strong>Rising Stars</strong>, and <strong>Niche Players</strong>. A company needs at least 5 verified reviews (with 3 recent) to be eligible for a leaderboard.
      </p>

      <p className="mt-8 rounded-lg border border-dashed border-border p-4 text-sm text-muted-foreground">
        Note: the current scores are demo values seeded for development. The full deterministic engine (with Bayesian shrinkage, recency decay, and cohort snapshots) is specified in the build docs and lands in milestone M6.
      </p>

      <p className="mt-6 text-sm">
        <Link href="/companies" className="text-primary hover:underline">Browse the directory →</Link>
      </p>
    </main>
  );
}
